sudo: false

cache:
  directories:
    - $HOME/.composer/cache

language: php

php:
  - 7.0
  - 7.1

before_script:
  - composer install --prefer-dist --classmap-authoritative --no-interaction --no-progress

script: composer test
